export const SET_PERSONS = 'GET_PERSONS';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const SET_VISIBLE = 'SET_VISIBLE';

export const GET_PERSONS_REQUEST = 'GET_PERSONS_REQUEST';
export const POST_PERSON_REQUEST = 'POST_PERSON_REQUEST';
export const UPDATE_PERSON_REQUEST = 'UPDATE_PERSON_REQUEST';
export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
